const data = [
  {
    _id: '1',
    name: 'Senna',
    image: '../images/McLaren/Senna/thumbnail.jpg',
    description:
      'McLaren Senna 4.0-liter Twin-Turbo V8 Gas 7-Speed + Reverse Seamless Shift Gearbox (SSG) Coupe',
    brand: 'McLaren',
    category: 'Coupe',
    price: 229229,
    rating: 4.5,
    year: 2011,
    priceIncrease: '15%',
  },
  {
    _id: '2',
    name: 'McLaren 570S Spider',
    image: '../images/McLaren/570S_Spider/thumbnail.jpg',
    description:
      'MacLaren 570S Spider 3.8-liter Twin-Turbo V8 Gas 7-Speed Automatic',
    brand: 'MacLaren',
    category: 'Convertible',
    price: 339339,
    rating: 5.0,
    year: 2018,
    priceIncrease: '10%',
  },
  {
    _id: '3',
    name: 'McLaren GT',
    image: '../images/McLaren/GT/thumbnail.jpg',
    description: 'McLaren GT 4.0-liter Twin-Turbo V8 Gas 7-Speed Automatic',
    brand: 'McLaren',
    category: 'Coupe',
    price: 299929,
    rating: 5,
    year: 2019,
    priceIncrease: '8%',
  },
  {
    _id: '4',
    name: 'Sian FKP 37',
    image: '../images/Lamborghini/Sain_FKP_37/thumbnail.jpg',
    description:
      'Lamborghini Sian FKP 37 6.5-liter V12 Hybrid 7-Speed ISR Semi-Automatic',
    brand: 'Lamborghini',
    category: 'Coupe',
    price: 399399,
    rating: 5,
    year: 2012,
    priceIncrease: '9%',
  },
  {
    _id: '5',
    name: 'Aventador SVJ',
    image: '../images/Lamborghini/Aventador_SVJ/thumbnail.jpg',
    description:
      'Lamborghini Aventador SVJ 6.5-liter V12 Gas 7-Speed Automatic',
    brand: 'Lamborghini',
    category: 'Coupe',
    price: 499449,
    rating: 5,
    year: 2017,
    priceIncrease: '12%',
  },
  {
    _id: '6',
    name: 'Huracan Evo',
    image: '../images/Lamborghini/Huracan_Evo/thumbnail.jpg',
    description: 'Lamborghini Huracan Evo 5.2-liter V10 Gas 7-Speed Automatic',
    brand: 'Lamborghini',
    category: 'Coupe',
    price: 299299,
    rating: 5,
    year: 2018,
    priceIncrease: '10%',
  },
  {
    _id: '7',
    name: '812 Superfast',
    image: '../images/Ferrari/812_Superfast/thumbnail.jpg',
    description: 'Ferrari 812 Superfast 6.5-liter V12 Gas 7-Speed Automatic',
    brand: 'Ferrari',
    category: 'Coupe',
    price: 499429,
    rating: 4.5,
    year: 2016,
    priceIncrease: '22%',
  },
  {
    _id: '8',
    name: 'LaFerrari',
    image: '../images/Ferrari/LaFerrari/thumbnail.jpg',
    description: 'LaFerrari 6.3-liter V12 Hybrid 7-Speed Automatic',
    brand: 'Ferrari',
    category: 'Coupe',
    price: 329999,
    rating: 5,
    year: 2019,
    priceIncrease: '7%',
  },
  {
    _id: '9',
    name: '488 Spider',
    image: '../images/Lamborghini/Huracan_Evo/thumbnail.jpg',
    description:
      'Ferrari 488 Spider 3.9-liter Twin-Turbo V8 Gas 7-Speed Automatic',
    brand: 'Ferrari',
    category: 'Convertible',
    price: 499229,
    rating: 4.5,
    year: 2015,
    priceIncrease: '9%',
  },
  {
    _id: '10',
    name: 'Chiron',
    image: '../images/Bugatti/Chiron/thumbnail.jpg',
    description: 'Bugatti Chiron 8.0-liter W16 Gas 7-Speed Dual Clutch',
    brand: 'Bugatti',
    category: 'Coupe',
    price: 399229,
    rating: 5,
    year: 2014,
    priceIncrease: '11%',
  },
  {
    _id: '11',
    name: 'Divo',
    image: '../images/Bugatti/Divo/thumbnail.jpg',
    description: 'Bugatti Divo 8.0-liter W16 Gas 7-Speed DSG',
    brand: 'Bugatti',
    category: 'Coupe',
    price: 399229,
    rating: 4.5,
    year: 2012,
    priceIncrease: '15%',
  },
  {
    _id: '12',
    name: 'Veyron 16.4',
    image: '../images/Bugatti/Veyron_16.4/thumbnail.jpg',
    description:
      'Bugatti Veyron 16.4 8.0-liter W16 Gas 7-Speed Direct Shift Automatic',
    brand: 'Bugatti',
    category: 'Coupe',
    price: 599229,
    rating: 5,
    year: 2019,
    priceIncrease: '5%',
  },
];

export default data;
